source 'https://cdn.cocoapods.org/'

platform :ios, '11.0'
use_frameworks!

target 'TrustedForm_Demo' do
  pod 'TrustedForm', :git => 'https://github.com/activeprospect/trustedform-ios-sdk.git', :branch => '0.2.1dev'
  pod 'IQKeyboardManagerSwift'
end
